export interface AAAStadium {
  id: string;
  slug: string;
  name: string;
  team: string;
  minorLeague: "IL" | "PCL";
  mlbAffiliate: string;
  city: string;
  state: string;
  capacity: number;
  yearOpened: number;
  coordinates: { lat: number; lng: number };
  description: string;
  funFacts: string[];
  imageColor: string;
}

export const aaaStadiums: AAAStadium[] = [
  // ── International League ──────────────────────────────────────────────────
  {
    id: "autozone-park",
    slug: "autozone-park",
    name: "AutoZone Park",
    team: "Memphis Redbirds",
    minorLeague: "IL",
    mlbAffiliate: "Toronto Blue Jays affiliate",
    city: "Memphis",
    state: "TN",
    capacity: 10000,
    yearOpened: 2000,
    coordinates: { lat: 35.14306, lng: -90.04917 },
    description:
      "A gorgeous brick downtown ballpark on the edge of Memphis's Beale Street entertainment district, AutoZone Park set a new standard for minor league design when it opened in 2000.",
    funFacts: [
      "AutoZone, the park's namesake, is headquartered just blocks away in downtown Memphis.",
      "The park was part of a broader downtown revitalization that transformed the South Main arts district.",
      "It served as the Cardinals' AAA affiliate for over two decades before switching to the Blue Jays.",
    ],
    imageColor: "bg-blue-600",
  },
  {
    id: "chs-field",
    slug: "chs-field",
    name: "CHS Field",
    team: "St. Paul Saints",
    minorLeague: "IL",
    mlbAffiliate: "Minnesota Twins affiliate",
    city: "Saint Paul",
    state: "MN",
    capacity: 7210,
    yearOpened: 2015,
    coordinates: { lat: 44.95086, lng: -93.08419 },
    description:
      "Nestled in St. Paul's revitalized Lowertown neighborhood, CHS Field is an intimate urban ballpark that anchored the transformation of a once-dormant rail yard into a thriving arts and entertainment hub.",
    funFacts: [
      "The Saints were a beloved independent team for 23 years before joining affiliated baseball as the Twins' AAA club in 2021.",
      "CHS Inc., the park's namesake, is one of the largest agricultural cooperatives in the country, headquartered near the Twin Cities.",
      "The park's location in Lowertown St. Paul puts fans within walking distance of Union Depot and the Green Line light rail.",
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "coca-cola-park",
    slug: "coca-cola-park",
    name: "Coca-Cola Park",
    team: "Lehigh Valley IronPigs",
    minorLeague: "IL",
    mlbAffiliate: "Philadelphia Phillies affiliate",
    city: "Allentown",
    state: "PA",
    capacity: 10100,
    yearOpened: 2008,
    coordinates: { lat: 40.62611, lng: -75.45250 },
    description:
      "Home to the IronPigs — named for the molten pig iron byproduct of the region's storied steel industry — Coca-Cola Park is one of the best-attended minor league parks in the country.",
    funFacts: [
      "The park features a giant pig-themed weather vane atop the scoreboard that has become an iconic landmark.",
      "The IronPigs routinely rank in the top five for minor league attendance, often drawing over 500,000 fans per season.",
      "Located in the Lehigh Valley, the park draws from the Philadelphia suburbs and Allentown-Bethlehem metro area.",
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "durham-bulls-athletic-park",
    slug: "durham-bulls-athletic-park",
    name: "Durham Bulls Athletic Park",
    team: "Durham Bulls",
    minorLeague: "IL",
    mlbAffiliate: "Tampa Bay Rays affiliate",
    city: "Durham",
    state: "NC",
    capacity: 10000,
    yearOpened: 1995,
    coordinates: { lat: 35.99169, lng: -78.90419 },
    description:
      "The Durham Bulls are arguably the most famous team in minor league baseball, thanks to the 1988 film Bull Durham. The current ballpark, opened in 1995, carries on that legacy with a first-class facility that consistently ranks among the best in the minors.",
    funFacts: [
      "The film Bull Durham was actually shot at the old Durham Athletic Park — still standing nearby and still hosting events.",
      "The famous \"Hit Bull, Win Steak\" sign from the movie is recreated at DBAP, and a bull in left field blows smoke when a Bull homers.",
      "The Bulls have been one of the most successful AAA franchises in history, with deep ties to the Tampa Bay Rays development pipeline.",
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "esl-ballpark",
    slug: "esl-ballpark",
    name: "ESL Ballpark",
    team: "Rochester Red Wings",
    minorLeague: "IL",
    mlbAffiliate: "Washington Nationals affiliate",
    city: "Rochester",
    state: "NY",
    capacity: 10840,
    yearOpened: 1997,
    coordinates: { lat: 43.15827, lng: -77.61979 },
    description:
      "Originally built on the site of a former rail yard in downtown Rochester, ESL Ballpark (formerly Frontier Field) has been home to the Red Wings — one of the longest-operating franchises in minor league baseball.",
    funFacts: [
      "The Rochester Red Wings have played continuously since 1899, making them one of the oldest franchises in professional baseball.",
      "The park was renamed ESL Ballpark in 2022 after ESL Federal Credit Union acquired naming rights.",
      "Rochester served as the top affiliate of the Baltimore Orioles for decades before switching to the Washington Nationals.",
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "fifth-third-field",
    slug: "fifth-third-field",
    name: "Fifth Third Field",
    team: "Toledo Mud Hens",
    minorLeague: "IL",
    mlbAffiliate: "Detroit Tigers affiliate",
    city: "Toledo",
    state: "OH",
    capacity: 10300,
    yearOpened: 2002,
    coordinates: { lat: 41.64833, lng: -83.53889 },
    description:
      "Home to the wonderfully named Toledo Mud Hens — one of the most recognizable team names in all of baseball — Fifth Third Field has been a centerpiece of downtown Toledo's revitalization since 2002.",
    funFacts: [
      "The Mud Hens' name dates to the late 1800s, inspired by the American coot (a marsh bird) that populated the wetlands where the team originally played.",
      "M*A*S*H's Corporal Maxwell Klinger famously wore a Toledo Mud Hens hat, giving the team nationwide recognition.",
      "Fifth Third Field was built on the footprint of a former railroad hub, and the Mud Hens have been a Tigers affiliate since 1987.",
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "first-horizon-park",
    slug: "first-horizon-park",
    name: "First Horizon Park",
    team: "Nashville Sounds",
    minorLeague: "IL",
    mlbAffiliate: "Milwaukee Brewers affiliate",
    city: "Nashville",
    state: "TN",
    capacity: 10000,
    yearOpened: 2015,
    coordinates: { lat: 36.17278, lng: -86.78472 },
    description:
      "Opened in 2015 near downtown Nashville's bustling entertainment corridor, First Horizon Park brought the Sounds out of the suburbs and into the heart of Music City just as Nashville's population was exploding.",
    funFacts: [
      "The park was built on a site adjacent to the historic Sulphur Dell, Nashville's ballpark from 1885 to 1978 — considered one of the most unusual playing fields in baseball history due to its extreme slope.",
      "First Horizon Park opened the same year Nashville's broader downtown building boom kicked into high gear.",
      "The Sounds switched from the Oakland A's to the Texas Rangers to the Milwaukee Brewers affiliations across their tenure at this park.",
    ],
    imageColor: "bg-yellow-500",
  },
  {
    id: "gwinnett-field",
    slug: "gwinnett-field",
    name: "Gwinnett Field",
    team: "Gwinnett Stripers",
    minorLeague: "IL",
    mlbAffiliate: "Atlanta Braves affiliate",
    city: "Lawrenceville",
    state: "GA",
    capacity: 10427,
    yearOpened: 2009,
    coordinates: { lat: 34.04058, lng: -83.99239 },
    description:
      "Built to MLB standards in rapidly growing Gwinnett County northeast of Atlanta, Gwinnett Field serves as the Braves' primary development hub and has produced a steady stream of Atlanta's most notable prospects.",
    funFacts: [
      "The park was designed from the outset to meet MLB facility requirements, making it one of the most MLB-ready venues in the minors.",
      "Gwinnett County is one of the fastest-growing counties in the United States, and the park serves an enormous suburban Atlanta market.",
      "The team rebranded from the Gwinnett Braves to the Gwinnett Stripers in 2018, drawing on Georgia's striped bass heritage.",
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "harbor-park",
    slug: "harbor-park",
    name: "Harbor Park",
    team: "Norfolk Tides",
    minorLeague: "IL",
    mlbAffiliate: "New York Mets affiliate",
    city: "Norfolk",
    state: "VA",
    capacity: 11856,
    yearOpened: 1993,
    coordinates: { lat: 36.84279, lng: -76.27887 },
    description:
      "Situated directly on the Elizabeth River waterfront in downtown Norfolk, Harbor Park is one of the most scenically situated ballparks in all of professional baseball. Naval ships are visible from the upper deck.",
    funFacts: [
      "Harbor Park was named the best minor league park in America by Baseball America in the early 2000s.",
      "The park's right-field wall faces the Elizabeth River, and outfield home runs have been known to splash into the water.",
      "Norfolk has one of the largest naval bases in the world, and military appreciation events are a major part of the Tides' game-day experience.",
    ],
    imageColor: "bg-blue-500",
  },
  {
    id: "huntington-park",
    slug: "huntington-park",
    name: "Huntington Park",
    team: "Columbus Clippers",
    minorLeague: "IL",
    mlbAffiliate: "Cleveland Guardians affiliate",
    city: "Columbus",
    state: "OH",
    capacity: 10100,
    yearOpened: 2009,
    coordinates: { lat: 39.96862, lng: -83.01074 },
    description:
      "Widely regarded as one of the finest AAA parks in the country, Huntington Park anchors Columbus's Arena District — a model of urban entertainment development that has been replicated in cities across North America.",
    funFacts: [
      "Huntington Park won Baseball America's Best Double-A/Triple-A Ballpark award in its first year of operation.",
      "The Arena District surrounding the park includes Nationwide Arena (NHL), restaurants, hotels, and a concert venue — all built around the ballpark.",
      "The park replaced Cooper Stadium, which had served as Columbus's home since 1977.",
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "louisville-slugger-field",
    slug: "louisville-slugger-field",
    name: "Louisville Slugger Field",
    team: "Louisville Bats",
    minorLeague: "IL",
    mlbAffiliate: "Boston Red Sox affiliate",
    city: "Louisville",
    state: "KY",
    capacity: 13131,
    yearOpened: 2000,
    coordinates: { lat: 38.25619, lng: -85.74465 },
    description:
      "Named for the iconic bat brand manufactured in Louisville, Louisville Slugger Field sits at the heart of downtown Louisville near the Ohio River and the Louisville Slugger Museum — making it a pilgrimage destination for baseball fans.",
    funFacts: [
      "Hillerich & Bradsby, maker of the Louisville Slugger, has been based in Louisville since 1884 and supplies bats to the majority of MLB players.",
      "The park's brick exterior and design evoke the city's 19th-century industrial heritage, complementing the nearby museum's giant bat sculpture.",
      "At 13,131, Louisville Slugger Field has one of the largest capacities in Triple-A baseball.",
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "nbt-bank-stadium",
    slug: "nbt-bank-stadium",
    name: "NBT Bank Stadium",
    team: "Syracuse Mets",
    minorLeague: "IL",
    mlbAffiliate: "New York Mets affiliate",
    city: "Syracuse",
    state: "NY",
    capacity: 10815,
    yearOpened: 1997,
    coordinates: { lat: 43.07908, lng: -76.16536 },
    description:
      "Home to the Syracuse Mets — the direct AAA affiliate of the New York Mets — NBT Bank Stadium is a classic 1990s-era ballpark that has served as the proving ground for numerous major league callups over the decades.",
    funFacts: [
      "The park has gone through several naming rights changes, from P&C Stadium to Alliance Bank Stadium to its current name.",
      "Syracuse has hosted a professional baseball team nearly continuously since 1877, making it one of the oldest baseball markets in the country.",
      "The Mets connection means fans regularly see top prospects just weeks before their Citi Field debut.",
    ],
    imageColor: "bg-blue-500",
  },
  {
    id: "pnc-field",
    slug: "pnc-field",
    name: "PNC Field",
    team: "Scranton/WB RailRiders",
    minorLeague: "IL",
    mlbAffiliate: "New York Yankees affiliate",
    city: "Moosic",
    state: "PA",
    capacity: 10000,
    yearOpened: 1989,
    coordinates: { lat: 41.36041, lng: -75.68397 },
    description:
      "As the New York Yankees' top affiliate, PNC Field has served as one of the most watched addresses in minor league baseball — every high-profile Yankees prospect eventually passes through Moosic before reaching the Bronx.",
    funFacts: [
      "The park underwent a major renovation in 2013 when it was rebuilt nearly from scratch to meet Yankees standards.",
      "The Scranton/Wilkes-Barre market is one of the largest AAA markets in the country, sitting between two major metro areas in northeastern Pennsylvania.",
      "Numerous Yankees legends passed through the RailRiders roster, including Derek Jeter during his rehab assignments.",
    ],
    imageColor: "bg-slate-700",
  },
  {
    id: "polar-park",
    slug: "polar-park",
    name: "Polar Park",
    team: "Worcester Red Sox",
    minorLeague: "IL",
    mlbAffiliate: "Boston Red Sox affiliate",
    city: "Worcester",
    state: "MA",
    capacity: 9508,
    yearOpened: 2021,
    coordinates: { lat: 42.25694, lng: -71.80000 },
    description:
      "The newest park in the International League, Polar Park opened in 2021 as the centerpiece of Worcester's Canal District redevelopment — bringing affiliated baseball back to New England's second-largest city for the first time in decades.",
    funFacts: [
      "Polar Park replaced McCoy Stadium in Pawtucket, RI, which had been the Red Sox's AAA home for 51 years.",
      "The park is named for Polar Beverages, a Worcester-based company that has been producing seltzer water since 1882.",
      "Opening in 2021 amid the COVID pandemic, Polar Park's first full season with fans was 2022.",
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "principal-park",
    slug: "principal-park",
    name: "Principal Park",
    team: "Iowa Cubs",
    minorLeague: "IL",
    mlbAffiliate: "Chicago Cubs affiliate",
    city: "Des Moines",
    state: "IA",
    capacity: 11500,
    yearOpened: 1992,
    coordinates: { lat: 41.58028, lng: -93.61583 },
    description:
      "Principal Park sits along the Des Moines River in downtown Des Moines and has been home to the Iowa Cubs — longtime top affiliate of the Chicago Cubs — since 1992. The red brick exterior is an intentional nod to Wrigley Field.",
    funFacts: [
      "The Iowa Cubs have been the Chicago Cubs' AAA affiliate for most of the franchise's history, dating back to 1981.",
      "Principal Financial Group, the park's namesake, is a Fortune 500 insurance and financial services company headquartered in Des Moines.",
      "The park is situated right along the Des Moines River, and occasional high-water events have led to memorable postponements.",
    ],
    imageColor: "bg-blue-600",
  },
  {
    id: "sahlen-field",
    slug: "sahlen-field",
    name: "Sahlen Field",
    team: "Buffalo Bisons",
    minorLeague: "IL",
    mlbAffiliate: "Toronto Blue Jays affiliate",
    city: "Buffalo",
    state: "NY",
    capacity: 16600,
    yearOpened: 1988,
    coordinates: { lat: 42.88131, lng: -78.87428 },
    description:
      "The oldest park currently in use in the International League, Sahlen Field has been a downtown Buffalo institution since 1988. It earned international attention in 2020 when the Toronto Blue Jays played their home games there during the pandemic.",
    funFacts: [
      "Sahlen Field hosted actual MLB regular-season and playoff games in 2020 when the Blue Jays were unable to play in Canada due to COVID-19 border restrictions.",
      "At 16,600 capacity, it is the largest ballpark in Triple-A baseball.",
      "The park is named for Sahlen's, a Buffalo-founded meat and hot dog company whose franks are a signature ballpark food.",
    ],
    imageColor: "bg-blue-500",
  },
  {
    id: "truist-field",
    slug: "truist-field",
    name: "Truist Field",
    team: "Charlotte Knights",
    minorLeague: "IL",
    mlbAffiliate: "Chicago White Sox affiliate",
    city: "Charlotte",
    state: "NC",
    capacity: 10200,
    yearOpened: 2014,
    coordinates: { lat: 35.22799, lng: -80.84901 },
    description:
      "Located in uptown Charlotte just steps from Bank of America Stadium, Truist Field brought the Knights in from the suburbs in 2014 and placed them at the center of one of the fastest-growing cities in the Southeast.",
    funFacts: [
      "The Knights had played in suburban Fort Mill, SC, for 24 years before moving to uptown Charlotte.",
      "The park is named for Truist Financial, formed by the merger of BB&T and SunTrust Banks — both headquartered in the Carolinas/Southeast.",
      "On clear days, the Uptown Charlotte skyline forms a dramatic backdrop behind center field.",
    ],
    imageColor: "bg-gray-700",
  },
  {
    id: "victory-field",
    slug: "victory-field",
    name: "Victory Field",
    team: "Indianapolis Indians",
    minorLeague: "IL",
    mlbAffiliate: "Pittsburgh Pirates affiliate",
    city: "Indianapolis",
    state: "IN",
    capacity: 13750,
    yearOpened: 1996,
    coordinates: { lat: 39.76500, lng: -86.16833 },
    description:
      "Repeatedly voted the best minor league park in America by Baseball America, Victory Field is situated adjacent to White River State Park in downtown Indianapolis — combining natural scenery with a first-class baseball experience.",
    funFacts: [
      "Victory Field won Baseball America's Best Minor League Ballpark award multiple times, cementing its reputation as the gold standard of AAA parks.",
      "The park's location in White River State Park puts it next to the Indianapolis Zoo, the Indiana State Museum, and the NCAA Hall of Champions.",
      "It replaced Bush Stadium, where the Indians had played since 1931.",
    ],
    imageColor: "bg-yellow-600",
  },
  {
    id: "vystar-ballpark",
    slug: "vystar-ballpark",
    name: "VyStar Ballpark",
    team: "Jacksonville Jumbo Shrimp",
    minorLeague: "IL",
    mlbAffiliate: "Miami Marlins affiliate",
    city: "Jacksonville",
    state: "FL",
    capacity: 11000,
    yearOpened: 2003,
    coordinates: { lat: 30.32497, lng: -81.64307 },
    description:
      "Situated on the north bank of the St. Johns River in downtown Jacksonville, VyStar Ballpark offers some of the most unique sightlines in minor league baseball — with the river and the city's dramatic Hart Bridge as a backdrop.",
    funFacts: [
      "The team rebranded from the Jacksonville Suns to the Jacksonville Jumbo Shrimp in 2017, embracing a fun identity rooted in the Gulf Coast seafood tradition.",
      "VyStar Credit Union, the park's namesake, is one of the largest credit unions in Florida and is headquartered in Jacksonville.",
      "The park was previously known as The Baseball Grounds of Jacksonville, a name that itself became something of a local landmark.",
    ],
    imageColor: "bg-teal-600",
  },
  {
    id: "werner-park",
    slug: "werner-park",
    name: "Werner Park",
    team: "Omaha Storm Chasers",
    minorLeague: "IL",
    mlbAffiliate: "Kansas City Royals affiliate",
    city: "Papillon",
    state: "NE",
    capacity: 9023,
    yearOpened: 2011,
    coordinates: { lat: 41.15196, lng: -96.10639 },
    description:
      "Built in suburban Papillon to replace the legendary Rosenblatt Stadium, Werner Park is the home of the Omaha Storm Chasers and sits just south of the Omaha metro in one of the fastest-growing parts of Nebraska.",
    funFacts: [
      "Rosenblatt Stadium, the park's predecessor, was the iconic home of the NCAA College World Series from 1950 to 2010.",
      "Werner Enterprises, a major Omaha-based trucking and logistics company, holds the park's naming rights.",
      "The Storm Chasers' name pays homage to Tornado Alley — the region of the central US prone to severe thunderstorms and tornadoes.",
    ],
    imageColor: "bg-blue-600",
  },

  // ── Pacific Coast League ──────────────────────────────────────────────────
  {
    id: "cheney-stadium",
    slug: "cheney-stadium",
    name: "Cheney Stadium",
    team: "Tacoma Rainiers",
    minorLeague: "PCL",
    mlbAffiliate: "Seattle Mariners affiliate",
    city: "Tacoma",
    state: "WA",
    capacity: 6500,
    yearOpened: 1960,
    coordinates: { lat: 47.23803, lng: -122.49754 },
    description:
      "One of the oldest continuously operating minor league parks in the country, Cheney Stadium underwent a transformative renovation in 2011 that preserved its intimate character while adding modern amenities. The views of Mount Rainier on clear days are unmatched.",
    funFacts: [
      "Cheney Stadium opened in 1960 and was named for Ben Cheney, a local timber magnate who helped fund its construction.",
      "The 2011 renovation reduced capacity from over 9,000 to a more intimate 6,500, improving the fan experience dramatically.",
      "On clear days, Mount Rainier looms over the outfield, making it one of the most visually stunning backdrops in professional baseball.",
    ],
    imageColor: "bg-teal-700",
  },
  {
    id: "chickasaw-bricktown-ballpark",
    slug: "chickasaw-bricktown-ballpark",
    name: "Chickasaw Bricktown Ballpark",
    team: "Oklahoma City Comets",
    minorLeague: "PCL",
    mlbAffiliate: "Los Angeles Dodgers affiliate",
    city: "Oklahoma City",
    state: "OK",
    capacity: 9000,
    yearOpened: 1998,
    coordinates: { lat: 35.46496, lng: -97.50805 },
    description:
      "The anchor of Oklahoma City's Bricktown entertainment district, Chickasaw Bricktown Ballpark has been at the center of one of the most successful urban revitalization stories in the American Midwest — helping transform a once-derelict warehouse district into a thriving destination.",
    funFacts: [
      "Bricktown was a near-abandoned warehouse district before the ballpark opened in 1998; today it is OKC's premier entertainment zone.",
      "The park is named for the Chickasaw Nation, a sovereign Native American nation whose territory historically encompasses much of southern Oklahoma.",
      "The team was rebranded from the Oklahoma City Dodgers to the Oklahoma City Comets in 2024.",
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "constellation-field",
    slug: "constellation-field",
    name: "Constellation Field",
    team: "Sugar Land Space Cowboys",
    minorLeague: "PCL",
    mlbAffiliate: "Houston Astros affiliate",
    city: "Sugar Land",
    state: "TX",
    capacity: 7500,
    yearOpened: 2012,
    coordinates: { lat: 29.62275, lng: -95.64718 },
    description:
      "Home to the Space Cowboys — a name that pays tribute to both Houston's NASA legacy and Texas's cowboy culture — Constellation Field is a modern suburban ballpark serving one of the fastest-growing counties in the United States.",
    funFacts: [
      "The Space Cowboys name was adopted in 2022, referencing the NASA Johnson Space Center located nearby in Houston.",
      "Fort Bend County, where Sugar Land is located, was one of the fastest-growing counties in the US through the 2010s and 2020s.",
      "Constellation Field was built as a public-private partnership and serves as an economic anchor for the Sugar Land Town Square development.",
    ],
    imageColor: "bg-orange-500",
  },
  {
    id: "dell-diamond",
    slug: "dell-diamond",
    name: "Dell Diamond",
    team: "Round Rock Express",
    minorLeague: "PCL",
    mlbAffiliate: "Texas Rangers affiliate",
    city: "Round Rock",
    state: "TX",
    capacity: 11631,
    yearOpened: 2000,
    coordinates: { lat: 30.52730, lng: -97.63050 },
    description:
      "Named for Dell Technologies, which was founded in Round Rock and remains one of the city's largest employers, Dell Diamond has been one of the most consistently well-attended minor league parks in the country since opening in 2000.",
    funFacts: [
      "The Round Rock Express were co-owned by Nolan Ryan and his son Reid for years, lending the franchise an outsized profile.",
      "Dell Inc. was founded by Michael Dell in Austin in 1984 and relocated its headquarters to Round Rock in 1994.",
      "At 11,631 capacity, Dell Diamond regularly ranks among the top five in minor league attendance.",
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "greater-nevada-field",
    slug: "greater-nevada-field",
    name: "Greater Nevada Field",
    team: "Reno Aces",
    minorLeague: "PCL",
    mlbAffiliate: "Arizona Diamondbacks affiliate",
    city: "Reno",
    state: "NV",
    capacity: 9013,
    yearOpened: 2009,
    coordinates: { lat: 39.52900, lng: -119.80800 },
    description:
      "Located in downtown Reno, Greater Nevada Field is well-known throughout the PCL for its hitter-friendly conditions — the combination of altitude, dry air, and Nevada heat creates one of the most homer-happy environments in professional baseball.",
    funFacts: [
      "Reno sits at 4,500 feet of elevation, contributing to the park's notorious reputation as a hitters' paradise.",
      "The Aces joined the PCL as an expansion team in 2009, the same year the park opened.",
      "Greater Nevada Credit Union, the park's namesake, is the largest credit union headquartered in Nevada.",
    ],
    imageColor: "bg-purple-600",
  },
  {
    id: "las-vegas-ballpark",
    slug: "las-vegas-ballpark",
    name: "Las Vegas Ballpark",
    team: "Las Vegas Aviators",
    minorLeague: "PCL",
    mlbAffiliate: "Athletics affiliate",
    city: "Las Vegas",
    state: "NV",
    capacity: 10000,
    yearOpened: 2019,
    coordinates: { lat: 36.15228, lng: -115.32942 },
    description:
      "One of the newest and most lavish parks in all of professional baseball, Las Vegas Ballpark opened in 2019 in Downtown Summerlin and features a pool beyond the outfield wall — quintessentially Vegas.",
    funFacts: [
      "The pool in the outfield can be rented for group events and holds up to 34 people during games.",
      "The ballpark was built in anticipation of the Oakland Athletics eventually relocating to Las Vegas — a move that materialized in 2025.",
      "Despite the MLB-quality facility, the extreme Las Vegas summer heat pushes game times to evenings and limits day games almost entirely.",
    ],
    imageColor: "bg-green-700",
  },
  {
    id: "isotopes-park",
    slug: "isotopes-park",
    name: "Rio Grande CU Field at Isotopes Park",
    team: "Albuquerque Isotopes",
    minorLeague: "PCL",
    mlbAffiliate: "Colorado Rockies affiliate",
    city: "Albuquerque",
    state: "NM",
    capacity: 13500,
    yearOpened: 2003,
    coordinates: { lat: 35.06972, lng: -106.62917 },
    description:
      "Home to the Albuquerque Isotopes — whose very name was inspired by a Simpsons episode — Isotopes Park sits at over 5,000 feet of elevation, making it one of the most homer-friendly parks on the planet and a nightmare for pitching statistics.",
    funFacts: [
      "The team's name was inspired by the 2001 Simpsons episode \"Hungry, Hungry Homer,\" in which Homer discovers the Springfield Isotopes plan to move to Albuquerque.",
      "At 5,312 feet of elevation, the park's thin air significantly increases fly ball distance — resulting in some of the highest-scoring games in minor league baseball.",
      "The Isotopes had a previous stint as a PCL franchise in the 1960s before being revived in 2003 with the new stadium.",
    ],
    imageColor: "bg-purple-700",
  },
  {
    id: "southwest-university-park",
    slug: "southwest-university-park",
    name: "Southwest University Park",
    team: "El Paso Chihuahuas",
    minorLeague: "PCL",
    mlbAffiliate: "San Diego Padres affiliate",
    city: "El Paso",
    state: "TX",
    capacity: 9500,
    yearOpened: 2014,
    coordinates: { lat: 31.75903, lng: -106.49267 },
    description:
      "Perched on the US-Mexico border in downtown El Paso, Southwest University Park is one of the most geographically dramatic parks in professional baseball — with views into Ciudad Juárez, Mexico, visible from the upper concourse.",
    funFacts: [
      "The Franklin Mountains rise behind the outfield, and the park's location on the border gives it a uniquely binational fan base.",
      "The Chihuahuas were named for the breed of dog that originated in the Mexican state of Chihuahua, just across the border.",
      "The park was built as the anchor of a downtown El Paso revitalization effort that has transformed the city's urban core.",
    ],
    imageColor: "bg-amber-600",
  },
  {
    id: "sutter-health-park",
    slug: "sutter-health-park",
    name: "Sutter Health Park",
    team: "Sacramento River Cats",
    minorLeague: "PCL",
    mlbAffiliate: "San Francisco Giants affiliate",
    city: "Sacramento",
    state: "CA",
    capacity: 14014,
    yearOpened: 2000,
    coordinates: { lat: 38.58037, lng: -121.51380 },
    description:
      "Located on the banks of the Sacramento River in West Sacramento, Sutter Health Park is one of the most beloved and best-attended parks in the Pacific Coast League, regularly drawing some of the highest crowds in all of Triple-A baseball.",
    funFacts: [
      "The park is consistently among the top three in AAA attendance, often surpassing 500,000 fans per season.",
      "The Sacramento River beyond the outfield creates one of the most picturesque ballpark settings on the West Coast.",
      "Sutter Health Park is named for Sutter Health, a major Northern California hospital network with over 24 hospitals across the region.",
    ],
    imageColor: "bg-orange-600",
  },
  {
    id: "america-first-square",
    slug: "america-first-square",
    name: "The Ballpark at America First Square",
    team: "Salt Lake Bees",
    minorLeague: "PCL",
    mlbAffiliate: "Los Angeles Angels affiliate",
    city: "South Jordan",
    state: "UT",
    capacity: 8500,
    yearOpened: 2025,
    coordinates: { lat: 40.54970, lng: -112.02250 },
    description:
      "The newest ballpark in all of professional baseball, The Ballpark at America First Square opened in 2025 in South Jordan, Utah, replacing the aging Smith's Ballpark that had served Salt Lake City since 1994. The Wasatch Mountains provide a stunning backdrop.",
    funFacts: [
      "The Ballpark at America First Square is the newest park in all of professional baseball as of 2025.",
      "The Wasatch Range, visible beyond the outfield, provides some of the most dramatic mountain scenery of any ballpark in the country.",
      "America First Credit Union, the park's namesake, is one of the largest credit unions in the United States by membership.",
    ],
    imageColor: "bg-red-500",
  },
];

export const ilStadiums = aaaStadiums.filter((s) => s.minorLeague === "IL");
export const pclStadiums = aaaStadiums.filter((s) => s.minorLeague === "PCL");

export function getAAAStadiumBySlug(slug: string): AAAStadium | undefined {
  return aaaStadiums.find((s) => s.slug === slug);
}

export function getAllAAASlugs(): string[] {
  return aaaStadiums.map((s) => s.slug);
}
