export type Surface = "Natural Grass" | "Artificial Turf" | "Hybrid";
export type RoofType = "Open" | "Fixed Dome" | "Retractable" | "Partially Open";

export interface Stadium {
  id: string;
  slug: string;
  name: string;
  team: string;
  league: "AL" | "NL";
  division: "AL East" | "AL Central" | "AL West" | "NL East" | "NL Central" | "NL West";
  city: string;
  state: string;
  country: string;
  capacity: number;
  yearOpened: number;
  surface: Surface;
  roofType: RoofType;
  coordinates: { lat: number; lng: number };
  description: string;
  funFacts: string[];
  // Trip planning
  gettingThere: {
    transit: string;
    parking: string;
    rideshare: string;
  };
  stayNearby: {
    budget: { name: string; distance: string };
    midRange: { name: string; distance: string };
    luxury: { name: string; distance: string };
  };
  nearbyFood: Array<{ name: string; type: string; distance: string; note: string }>;
  imageColor: string; // Tailwind background color for placeholder
}

export const stadiums: Stadium[] = [
  {
    id: "oriole-park",
    slug: "oriole-park",
    name: "Oriole Park at Camden Yards",
    team: "Baltimore Orioles",
    league: "AL",
    division: "AL East",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    capacity: 45971,
    yearOpened: 1992,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 39.2839, lng: -76.6218 },
    description: "The ballpark that started the retro-classic movement. Camden Yards set the standard for modern stadium design by incorporating the historic B&O Warehouse into its right-field facade.",
    funFacts: [
      "The B&O Warehouse beyond right field is 432 feet from home plate — no ball has ever been hit out of the park to reach it in a game.",
      "Designed by HOK Sport, it was the first of the 'retro' ballparks that inspired a generation of new stadiums.",
      "The warehouse was built in 1905 and is the longest building on the East Coast at over 1,000 feet.",
    ],
    gettingThere: {
      transit: "MARC Train and Light Rail stop right outside at Camden Station. Easy ride from downtown Baltimore.",
      parking: "Lots B, C, and D surround the stadium. Lot B is closest to the main entrance. Arrive early on busy days.",
      rideshare: "Drop-off on Russell Street or Hamburg Street. Designated rideshare pickup zone post-game on Ostend St.",
    },
    stayNearby: {
      budget: { name: "Holiday Inn Baltimore Inner Harbor", distance: "0.4 mi" },
      midRange: { name: "Courtyard Baltimore Downtown/Inner Harbor", distance: "0.6 mi" },
      luxury: { name: "Four Seasons Hotel Baltimore", distance: "1.2 mi" },
    },
    nearbyFood: [
      { name: "Lexington Market", type: "Market / Food Hall", distance: "0.8 mi", note: "Historic indoor market with dozens of vendors since 1782." },
      { name: "Faidley's Seafood", type: "Seafood", distance: "0.9 mi", note: "Best crab cakes in Baltimore — cash only, worth it." },
      { name: "Pickles Pub", type: "Sports Bar", distance: "0.1 mi", note: "The closest bar to the ballpark, perfect for pregame." },
      { name: "LP Steamers", type: "Crab House", distance: "1.4 mi", note: "Classic Maryland steamed crabs on picnic tables." },
    ],
    imageColor: "bg-orange-500",
  },
  {
    id: "fenway-park",
    slug: "fenway-park",
    name: "Fenway Park",
    team: "Boston Red Sox",
    league: "AL",
    division: "AL East",
    city: "Boston",
    state: "MA",
    country: "USA",
    capacity: 37755,
    yearOpened: 1912,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 42.3467, lng: -71.0972 },
    description: "The oldest ballpark in Major League Baseball, Fenway Park opened on April 20, 1912 — the same day the Titanic sank. Home to the iconic Green Monster, it remains one of the sport's most beloved cathedrals.",
    funFacts: [
      "The Green Monster is 37 feet 2 inches tall and was originally built to block non-paying fans from watching games for free.",
      "Seat 21 in the right-field bleachers is painted red to mark where Ted Williams hit the longest measurable home run in Fenway history (502 feet) in 1946.",
      "Fenway Park is a Boston Landmark and on the National Register of Historic Places.",
    ],
    gettingThere: {
      transit: "Take the Green Line (B, C, or D branch) to Kenmore Station — a 5-minute walk to the park.",
      parking: "Very limited — not recommended. Garages nearby on Boylston St. Expect to pay $40+.",
      rideshare: "Drop-off on Yawkey Way (now Jersey Street). Pickup post-game on Boylston Street.",
    },
    stayNearby: {
      budget: { name: "Hostelling International Boston", distance: "1.5 mi" },
      midRange: { name: "The Inn at Longwood Medical", distance: "0.4 mi" },
      luxury: { name: "Hotel Commonwealth", distance: "0.2 mi" },
    },
    nearbyFood: [
      { name: "Eastern Standard", type: "American Brasserie", distance: "0.2 mi", note: "Classic pregame spot right across from Fenway." },
      { name: "Bleacher Bar", type: "Sports Bar", distance: "0.1 mi", note: "Bar built into the Green Monster with a window onto the outfield." },
      { name: "Tasty Burger", type: "Burgers", distance: "0.3 mi", note: "Affordable, filling pregame option on Yawkey." },
      { name: "Island Creek Oyster Bar", type: "Seafood", distance: "0.3 mi", note: "Stellar oysters and New England seafood in the Kenmore area." },
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "yankee-stadium",
    slug: "yankee-stadium",
    name: "Yankee Stadium",
    team: "New York Yankees",
    league: "AL",
    division: "AL East",
    city: "Bronx",
    state: "NY",
    country: "USA",
    capacity: 46537,
    yearOpened: 2009,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 40.8296, lng: -73.9262 },
    description: "The current Yankee Stadium opened in 2009 directly across from the original House That Ruth Built. It features a dramatic limestone and granite exterior evoking the original park and is consistently one of the top attendance draws in baseball.",
    funFacts: [
      "Construction cost $2.3 billion — the most expensive stadium ever built at the time.",
      "The stadium features a 59-foot HD scoreboard in center field, one of baseball's largest.",
      "The Monument Park, honoring Yankee greats, is accessible to fans before games.",
    ],
    gettingThere: {
      transit: "Take the 4, B, or D subway train to 161st Street–Yankee Stadium station — right at the front gate.",
      parking: "Garages adjacent to the stadium. Lot 1 is the most convenient. Expect $35–$50.",
      rideshare: "Drop-off on East 161st Street. Post-game pickup on Walton Avenue.",
    },
    stayNearby: {
      budget: { name: "Umbrella Hotel Bronx", distance: "0.5 mi" },
      midRange: { name: "Concourse Plaza Multiplex", distance: "1.0 mi" },
      luxury: { name: "The Westin New York Grand Central", distance: "7 mi (Midtown)" },
    },
    nearbyFood: [
      { name: "Bruckner Bar & Grill", type: "American", distance: "1.2 mi", note: "Popular Bronx sports bar with good wings." },
      { name: "Sam's Soul Food", type: "Soul Food", distance: "0.6 mi", note: "Legendary Bronx comfort food, great before a day game." },
      { name: "Zero Otto Nove", type: "Italian", distance: "1.5 mi", note: "Arthur Avenue's best pizza — a Bronx institution." },
      { name: "Papaye", type: "West African / Caribbean", distance: "0.8 mi", note: "Vibrant Ghanaian-Caribbean restaurant near the stadium." },
    ],
    imageColor: "bg-slate-800",
  },
  {
    id: "citi-field",
    slug: "citi-field",
    name: "Citi Field",
    team: "New York Mets",
    league: "NL",
    division: "NL East",
    city: "Flushing",
    state: "NY",
    country: "USA",
    capacity: 41922,
    yearOpened: 2009,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 40.7571, lng: -73.8458 },
    description: "Citi Field was designed to evoke the spirit of the old Ebbets Field and features a dramatic rotunda entrance honoring Jackie Robinson. It sits adjacent to the site of the old Shea Stadium in Flushing, Queens.",
    funFacts: [
      "The Jackie Robinson Rotunda entrance was inspired by Ebbets Field's dome and features 83-foot arched windows.",
      "The famous 'Home Run Apple' from Shea Stadium was moved to the outfield plaza.",
      "Citi Field is next to Arthur Ashe Stadium, home of the US Open tennis tournament.",
    ],
    gettingThere: {
      transit: "Take the 7 train to Mets-Willets Point station — the park is steps away. Also accessible via LIRR Port Washington branch.",
      parking: "Large lots surrounding the stadium. Lot A is closest to the main entrance.",
      rideshare: "Drop-off on 126th Street. Post-game pickup in the designated rideshare lot.",
    },
    stayNearby: {
      budget: { name: "Fairfield Inn & Suites Flushing", distance: "1.1 mi" },
      midRange: { name: "Hyatt Place Flushing", distance: "1.3 mi" },
      luxury: { name: "TWA Hotel at JFK", distance: "5 mi" },
    },
    nearbyFood: [
      { name: "Main Street Flushing", type: "Asian Food Hall", distance: "1.5 mi", note: "The best Asian food outside Asia — endless options." },
      { name: "New World Mall Food Court", type: "Chinese / Pan-Asian", distance: "1.4 mi", note: "Massive underground food court with regional Chinese cuisine." },
      { name: "Shake Shack", type: "Burgers", distance: "Inside stadium", note: "A Citi Field tradition — long lines but worth it." },
      { name: "Corner Bistro", type: "Bar & Burger", distance: "10 mi (Manhattan)", note: "Worth the trip for the legendary Bistro Burger." },
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "rogers-centre",
    slug: "rogers-centre",
    name: "Rogers Centre",
    team: "Toronto Blue Jays",
    league: "AL",
    division: "AL East",
    city: "Toronto",
    state: "ON",
    country: "Canada",
    capacity: 49286,
    yearOpened: 1989,
    surface: "Artificial Turf",
    roofType: "Retractable",
    coordinates: { lat: 43.6414, lng: -79.3894 },
    description: "Rogers Centre (formerly SkyDome) was the world's first stadium with a fully retractable roof when it opened in 1989. A landmark of downtown Toronto, it sits in the shadow of the CN Tower.",
    funFacts: [
      "The retractable roof covers 8 acres and takes 20 minutes to open or close.",
      "There is a hotel built into the stadium — some rooms overlook the field.",
      "It was the first stadium to host both a Super Bowl and a World Series.",
    ],
    gettingThere: {
      transit: "Walk from Union Station (TTC subway lines 1 and 2) — about 10 minutes. The PATH underground walkway also connects downtown.",
      parking: "Underground parking at the stadium. Street parking limited. GO Transit highly recommended.",
      rideshare: "Drop-off on Blue Jays Way. Post-game pickup at designated area on Bremner Blvd.",
    },
    stayNearby: {
      budget: { name: "HI Toronto Hostel", distance: "0.8 mi" },
      midRange: { name: "Marriott City Centre Hotel", distance: "0 mi (attached)" },
      luxury: { name: "The Ritz-Carlton Toronto", distance: "0.4 mi" },
    },
    nearbyFood: [
      { name: "Harbour Sixty Steakhouse", type: "Steakhouse", distance: "0.5 mi", note: "Upscale waterfront dining for a special game night." },
      { name: "The Loose Moose", type: "Sports Bar", distance: "0.1 mi", note: "Classic pregame bar with great patio on game days." },
      { name: "Bar Wellington", type: "Bar & Grill", distance: "0.2 mi", note: "Popular spot on King Street West for food and drinks." },
      { name: "Kensington Market", type: "Food District", distance: "1.5 mi", note: "Eclectic neighborhood with global street food." },
    ],
    imageColor: "bg-sky-600",
  },
  {
    id: "tropicana-field",
    slug: "tropicana-field",
    name: "Tropicana Field",
    team: "Tampa Bay Rays",
    league: "AL",
    division: "AL East",
    city: "St. Petersburg",
    state: "FL",
    country: "USA",
    capacity: 25000,
    yearOpened: 1990,
    surface: "Artificial Turf",
    roofType: "Fixed Dome",
    coordinates: { lat: 27.7683, lng: -82.6534 },
    description: "Tropicana Field is the only fixed-dome stadium in the majors and the smallest by capacity. The Rays have announced plans for a new open-air ballpark nearby, slated to open in 2028.",
    funFacts: [
      "The dome's slanted roof is made of Teflon-coated fiberglass and glows orange at night.",
      "There are four catwalks above the field — balls that hit them are in play under local ground rules.",
      "The Rays have one of the best win-per-dollar ratios in baseball despite consistently low attendance.",
    ],
    gettingThere: {
      transit: "Limited public transit. The Sunrunner BRT connects St. Pete Beach to downtown. Mostly drive-to.",
      parking: "Large surface lots directly adjacent to the stadium. Affordable at $10–$20.",
      rideshare: "Drop-off on 16th Street South. Pickup in the same area post-game.",
    },
    stayNearby: {
      budget: { name: "Comfort Inn & Suites St. Petersburg", distance: "1.5 mi" },
      midRange: { name: "The Birchwood Inn", distance: "1.8 mi" },
      luxury: { name: "Vinoy Renaissance St. Petersburg Resort", distance: "1.9 mi" },
    },
    nearbyFood: [
      { name: "Locale Market", type: "Food Hall", distance: "1.7 mi", note: "Upscale local food market and restaurant on the waterfront." },
      { name: "The Canopy", type: "American", distance: "1.8 mi", note: "Great rooftop bar with views of Tampa Bay." },
      { name: "Ferg's Sports Bar", type: "Sports Bar", distance: "0.3 mi", note: "The go-to Rays pregame spot, right near the stadium." },
      { name: "Sea Salt", type: "Seafood", distance: "1.9 mi", note: "Outstanding fresh seafood in downtown St. Pete." },
    ],
    imageColor: "bg-indigo-600",
  },
  {
    id: "guaranteed-rate-field",
    slug: "guaranteed-rate-field",
    name: "Guaranteed Rate Field",
    team: "Chicago White Sox",
    league: "AL",
    division: "AL Central",
    city: "Chicago",
    state: "IL",
    country: "USA",
    capacity: 40615,
    yearOpened: 1991,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 41.8299, lng: -87.6338 },
    description: "Guaranteed Rate Field (formerly Comiskey Park and U.S. Cellular Field) sits on the South Side of Chicago. It was the first of the modern era stadiums, designed to correct the excesses of cookie-cutter multipurpose venues.",
    funFacts: [
      "The original Comiskey Park, which stood across the street, was demolished in 1991 to create a parking lot.",
      "The exploding scoreboard in center field has been a White Sox tradition since Bill Veeck installed the first one in 1960.",
      "The upper deck is unusually steep — designed to bring fans closer to the action.",
    ],
    gettingThere: {
      transit: "Take the CTA Red Line to Sox-35th Station — directly connected to the stadium via pedestrian bridge.",
      parking: "Large lots on the north side of the stadium. Affordable at $15–$25.",
      rideshare: "Drop-off on West 35th Street. Rideshare pickup in Lot D post-game.",
    },
    stayNearby: {
      budget: { name: "HI Chicago Hostel", distance: "3 mi (Loop)" },
      midRange: { name: "Hyatt Place Chicago/Midway Airport", distance: "4 mi" },
      luxury: { name: "The Blackstone Hotel", distance: "3 mi (Loop)" },
    },
    nearbyFood: [
      { name: "Ricobene's", type: "Italian Beef / Pizza", distance: "0.7 mi", note: "A South Side institution. The breaded steak sandwich is legendary." },
      { name: "Calumet Fisheries", type: "Seafood", distance: "4 mi", note: "Smoked fish on the Calumet River — an authentic Chicago experience." },
      { name: "Schaller's Pump", type: "Tavern", distance: "0.5 mi", note: "Oldest South Side bar, perfect for a post-game beer." },
      { name: "Nicky's Hot Dogs", type: "Hot Dogs", distance: "1.2 mi", note: "South Side Chicago hot dogs done right." },
    ],
    imageColor: "bg-gray-900",
  },
  {
    id: "progressive-field",
    slug: "progressive-field",
    name: "Progressive Field",
    team: "Cleveland Guardians",
    league: "AL",
    division: "AL Central",
    city: "Cleveland",
    state: "OH",
    country: "USA",
    capacity: 34788,
    yearOpened: 1994,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 41.4962, lng: -81.6852 },
    description: "Progressive Field (formerly Jacobs Field) is widely regarded as one of the best baseball stadiums in the country. It helped spark the revitalization of downtown Cleveland and consistently ranks among the most fan-friendly parks.",
    funFacts: [
      "The park sold out 455 consecutive games from 1995 to 2001 — a then-MLB record.",
      "Progressive Field was a co-winner of Baseball America's Best Baseball Stadium in 2008.",
      "The park features a unique asymmetric left field area with a 19-foot wall.",
    ],
    gettingThere: {
      transit: "RTA Red Line to Tower City station, then a short walk. Or take the free Trolley on game days.",
      parking: "Multiple garages within 2 blocks. East 9th Street garage is closest.",
      rideshare: "Drop-off on Ontario Street. Rideshare pickup on Carnegie Avenue post-game.",
    },
    stayNearby: {
      budget: { name: "Drury Plaza Hotel Cleveland Downtown", distance: "0.3 mi" },
      midRange: { name: "Kimpton Schofield Hotel", distance: "0.5 mi" },
      luxury: { name: "The Westin Cleveland Downtown", distance: "0.2 mi" },
    },
    nearbyFood: [
      { name: "Lola Bistro", type: "American", distance: "0.5 mi", note: "Michael Symon's flagship restaurant — Cleveland's best." },
      { name: "East 4th Street", type: "Restaurant Row", distance: "0.3 mi", note: "Pedestrian street lined with excellent restaurants." },
      { name: "Great Lakes Brewing Co.", type: "Brewery", distance: "1.5 mi", note: "Award-winning Ohio craft brewery in the Ohio City neighborhood." },
      { name: "Barrio", type: "Tacos", distance: "0.4 mi", note: "Build-your-own tacos, great for pregame fuel." },
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "comerica-park",
    slug: "comerica-park",
    name: "Comerica Park",
    team: "Detroit Tigers",
    league: "AL",
    division: "AL Central",
    city: "Detroit",
    state: "MI",
    country: "USA",
    capacity: 41083,
    yearOpened: 2000,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 42.3390, lng: -83.0485 },
    description: "Comerica Park opened in 2000 and was a centerpiece of Detroit's downtown revitalization. The park features a massive tiger sculpture at the main entrance and unique touches throughout that celebrate the city's heritage.",
    funFacts: [
      "Two massive tiger sculptures guard the main entrance on Witherell Street.",
      "The park features a Ferris wheel and carousel with baseball-themed cars in the outfield concourse.",
      "Center field measures 420 feet — one of the deepest in baseball.",
    ],
    gettingThere: {
      transit: "QLine streetcar runs on Woodward Avenue nearby. SMART bus routes serve the area.",
      parking: "Multiple lots adjacent to the park. MDC parking structure is most convenient.",
      rideshare: "Drop-off on Witherell Street. Post-game rideshare on Adams Street.",
    },
    stayNearby: {
      budget: { name: "Detroit Foundation Hotel", distance: "0.4 mi" },
      midRange: { name: "Courtyard Detroit Downtown", distance: "0.5 mi" },
      luxury: { name: "Shinola Hotel", distance: "0.3 mi" },
    },
    nearbyFood: [
      { name: "Buddy's Pizza", type: "Detroit-Style Pizza", distance: "2.5 mi", note: "The original Detroit-style pizza — square, crispy, incredible." },
      { name: "Slows Bar BQ", type: "BBQ", distance: "1.2 mi", note: "Best BBQ in Detroit, in the Corktown neighborhood." },
      { name: "Mercury Bar & Grill", type: "Burgers / Bar", distance: "0.4 mi", note: "Classic Detroit sports bar near the stadium." },
      { name: "Supino Pizzeria", type: "Pizza", distance: "1.5 mi", note: "Thin-crust Neapolitan-style pizza in Eastern Market." },
    ],
    imageColor: "bg-blue-800",
  },
  {
    id: "kauffman-stadium",
    slug: "kauffman-stadium",
    name: "Kauffman Stadium",
    team: "Kansas City Royals",
    league: "AL",
    division: "AL Central",
    city: "Kansas City",
    state: "MO",
    country: "USA",
    capacity: 37903,
    yearOpened: 1973,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 39.0517, lng: -94.4803 },
    description: "Kauffman Stadium — affectionately known as 'The K' — features one of baseball's most beautiful outfield water spectaculars, with fountains and cascading waterfalls that light up the night sky.",
    funFacts: [
      "The outfield water spectacular stretches 322 feet and includes a 12-story-tall scoreboard.",
      "Kauffman Stadium is one of only two single-purpose baseball stadiums built in the 1970s still in use (the other is Oakland Coliseum, now torn down).",
      "Kansas City is the world capital of barbecue — and The K's BBQ stands are legendary.",
    ],
    gettingThere: {
      transit: "KC Streetcar does not reach the stadium. Game Day Express buses run from Union Station on select dates.",
      parking: "Large surface lots — very affordable at $10–$15. Arrive early to tailgate.",
      rideshare: "Drop-off and pickup on Blue Ridge Cutoff.",
    },
    stayNearby: {
      budget: { name: "Hampton Inn Kansas City Airport", distance: "4 mi" },
      midRange: { name: "Marriott Kansas City Country Club Plaza", distance: "5 mi" },
      luxury: { name: "The Fontaine", distance: "5 mi (Plaza)" },
    },
    nearbyFood: [
      { name: "Joe's Kansas City Bar-B-Que", type: "BBQ", distance: "4 mi", note: "In a gas station. The Z-Man sandwich is life-changing." },
      { name: "Arthur Bryant's", type: "BBQ", distance: "4.5 mi", note: "The 'House of Heavy' — KCʼs most storied BBQ joint since 1908." },
      { name: "The Belfry", type: "Bar & Grill", distance: "0.5 mi", note: "Nearby post-game spot close to the stadium." },
      { name: "Gates Bar-B-Q", type: "BBQ", distance: "3 mi", note: "Order at the counter: 'Hi may I help you?' is a KC tradition." },
    ],
    imageColor: "bg-blue-600",
  },
  {
    id: "target-field",
    slug: "target-field",
    name: "Target Field",
    team: "Minnesota Twins",
    league: "AL",
    division: "AL Central",
    city: "Minneapolis",
    state: "MN",
    country: "USA",
    capacity: 38544,
    yearOpened: 2010,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 44.9817, lng: -93.2781 },
    description: "Target Field brought outdoor baseball back to Minnesota after nearly two decades in the Metrodome. Built in the heart of downtown Minneapolis, it's considered one of the best urban ballparks in the country.",
    funFacts: [
      "Target Field was built entirely within the downtown Minneapolis skyline — an engineering feat requiring careful coordination with nearby rail lines.",
      "The park features a heated concourse to make cold April and September games more bearable.",
      "State-of-the-art snowmelt technology is built into the seats and concourses.",
    ],
    gettingThere: {
      transit: "Target Field Station is right at the main entrance — served by METRO Blue Line, Green Line, and Northstar Commuter Rail.",
      parking: "Multiple ramps within 2 blocks. The A-Ramp is attached to the stadium.",
      rideshare: "Drop-off on 5th Street North. Post-game pickup on 7th Street North.",
    },
    stayNearby: {
      budget: { name: "Holiday Inn Minneapolis Downtown", distance: "0.7 mi" },
      midRange: { name: "The Minneapolis Club Hotel", distance: "0.8 mi" },
      luxury: { name: "Loews Minneapolis Hotel", distance: "0.5 mi" },
    },
    nearbyFood: [
      { name: "Murray's Restaurant", type: "Steakhouse", distance: "0.8 mi", note: "A Minneapolis institution since 1946 — famous garlic bread." },
      { name: "Brit's Pub", type: "English Pub", distance: "0.7 mi", note: "Rooftop lawn bowling and great selection of beers." },
      { name: "Burger Jones", type: "Burgers", distance: "0.5 mi", note: "Fun and casual spot perfect for postgame." },
      { name: "Bachelor Farmer", type: "Scandinavian-American", distance: "0.4 mi", note: "Excellent farm-to-table restaurant in the North Loop." },
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "minute-maid-park",
    slug: "minute-maid-park",
    name: "Minute Maid Park",
    team: "Houston Astros",
    league: "AL",
    division: "AL West",
    city: "Houston",
    state: "TX",
    country: "USA",
    capacity: 41168,
    yearOpened: 2000,
    surface: "Natural Grass",
    roofType: "Retractable",
    coordinates: { lat: 29.7573, lng: -95.3555 },
    description: "Minute Maid Park features a retractable roof for Houston's brutal summers, a charming downtown location inside the historic Union Station, and Tal's Hill — a famous sloped incline in center field that was removed in 2016.",
    funFacts: [
      "The main entrance is through the historic Union Station, built in 1911.",
      "A full-size vintage locomotive runs along a track above the left-field wall when the Astros hit a home run.",
      "The retractable roof can open or close in 12 minutes.",
    ],
    gettingThere: {
      transit: "METRORail Red Line to Bell Station — directly across from the stadium.",
      parking: "Multiple garages nearby. The Convention Center garage is well-priced.",
      rideshare: "Drop-off on Texas Avenue. Post-game pickup near Avenida Houston.",
    },
    stayNearby: {
      budget: { name: "La Quinta Inn & Suites Houston Downtown", distance: "0.5 mi" },
      midRange: { name: "Marriott Marquis Houston", distance: "0.3 mi" },
      luxury: { name: "The Post Oak Hotel", distance: "4 mi" },
    },
    nearbyFood: [
      { name: "Pappas Bros. Steakhouse", type: "Steakhouse", distance: "0.8 mi", note: "Houston's finest steakhouse for a special occasion." },
      { name: "Irma's Southwest Grill", type: "Tex-Mex", distance: "0.4 mi", note: "Downtown institution since 1989 — no menu, they tell you what's cooking." },
      { name: "La Carafe", type: "Bar", distance: "0.5 mi", note: "Houston's oldest bar in a beautiful 1860 building." },
      { name: "Niko Niko's", type: "Greek", distance: "3 mi", note: "Legendary Greek diner — best gyro in Houston." },
    ],
    imageColor: "bg-orange-600",
  },
  {
    id: "angel-stadium",
    slug: "angel-stadium",
    name: "Angel Stadium",
    team: "Los Angeles Angels",
    league: "AL",
    division: "AL West",
    city: "Anaheim",
    state: "CA",
    country: "USA",
    capacity: 45517,
    yearOpened: 1966,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 33.8003, lng: -117.8827 },
    description: "Angel Stadium is the third-oldest active ballpark in Major League Baseball. Extensively renovated in 1997, it features a stunning rock pile waterfall in center field and is one of baseball's most fan-friendly venues.",
    funFacts: [
      "The Big A — the stadium's distinctive halo-topped scoreboard — was originally the primary scoreboard before being moved outside the stadium.",
      "The artificial rock formation with waterfalls in center field was added during the 1997 renovation.",
      "Shohei Ohtani played here from 2018–2023 before his historic move to the Dodgers.",
    ],
    gettingThere: {
      transit: "OCTA Bus or Anaheim Resort Transit on game days. Metrolink or Amtrak to Anaheim Station (1.5 miles away).",
      parking: "Stadium lots are enormous and affordable at $10. Arrive early for tailgating.",
      rideshare: "Drop-off on State College Boulevard. Designated pickup area post-game.",
    },
    stayNearby: {
      budget: { name: "Anaheim Majestic Garden Hotel", distance: "0.7 mi" },
      midRange: { name: "Marriott Anaheim", distance: "3 mi" },
      luxury: { name: "The Anaheim Hotel", distance: "2.5 mi" },
    },
    nearbyFood: [
      { name: "Anaheim Packing House", type: "Food Hall", distance: "1.5 mi", note: "Housed in a 1919 citrus packing house — dozens of vendors." },
      { name: "Playground Restaurant", type: "New American", distance: "1.6 mi", note: "One of Orange County's best restaurants, farm-to-fork." },
      { name: "In-N-Out Burger", type: "Burgers", distance: "0.7 mi", note: "A California tradition — the Double-Double is mandatory." },
      { name: "Katella Deli", type: "Deli", distance: "0.3 mi", note: "Classic pre-game deli right next to the stadium." },
    ],
    imageColor: "bg-red-600",
  },
  {
    id: "oakland-coliseum",
    slug: "oakland-coliseum",
    name: "Oakland Coliseum",
    team: "Oakland Athletics",
    league: "AL",
    division: "AL West",
    city: "Oakland",
    state: "CA",
    country: "USA",
    capacity: 46765,
    yearOpened: 1966,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 37.7516, lng: -122.2005 },
    description: "The A's have moved to Sacramento while a new ballpark is built in Las Vegas. Oakland Coliseum was baseball's last multipurpose stadium, and despite its quirks — Mt. Davis blocking the view — it was beloved by generations of Oakland fans.",
    funFacts: [
      "The Oakland A's were one of baseball's most famous 'Moneyball' teams, famously competing with a tiny payroll.",
      "The foul territory at the Coliseum was the largest in baseball — a significant advantage for fielders.",
      "The view of the Oakland hills beyond the outfield, before Mt. Davis was built, was one of baseball's most beautiful.",
    ],
    gettingThere: {
      transit: "BART Coliseum/Oakland Airport station is directly connected to the stadium via skybridge.",
      parking: "Large surface lots, very affordable.",
      rideshare: "Drop-off and pickup at the BART station entrance.",
    },
    stayNearby: {
      budget: { name: "Waterfront Hotel Oakland", distance: "4 mi" },
      midRange: { name: "Marriott Oakland City Center", distance: "3.5 mi" },
      luxury: { name: "The Claremont Club & Spa", distance: "5 mi" },
    },
    nearbyFood: [
      { name: "Everett & Jones BBQ", type: "BBQ", distance: "3 mi", note: "Oakland BBQ institution. Brisket and ribs." },
      { name: "Tacos Mi Rancho", type: "Mexican", distance: "2 mi", note: "Authentic Oakland Mexican tacos." },
      { name: "Duende", type: "Spanish", distance: "3.5 mi", note: "Excellent tapas and paella in downtown Oakland." },
      { name: "Bakesale Betty", type: "Sandwiches", distance: "3 mi", note: "Famous fried chicken sandwiches — line around the block." },
    ],
    imageColor: "bg-yellow-600",
  },
  {
    id: "t-mobile-park",
    slug: "t-mobile-park",
    name: "T-Mobile Park",
    team: "Seattle Mariners",
    league: "AL",
    division: "AL West",
    city: "Seattle",
    state: "WA",
    country: "USA",
    capacity: 47929,
    yearOpened: 1999,
    surface: "Natural Grass",
    roofType: "Retractable",
    coordinates: { lat: 47.5914, lng: -122.3325 },
    description: "T-Mobile Park (formerly Safeco Field) features a retractable roof that keeps rain out but leaves the sides open, preserving the feeling of outdoor baseball. It's widely considered one of the most beautiful ballparks in the country.",
    funFacts: [
      "The roof takes 10 minutes to open or close and covers 8.85 acres.",
      "The park features the world's largest piece of public art — a 70-foot-wide wall mural in left-center field.",
      "Ichiro Suzuki played here from 2001–2012 and 2018–2019, becoming a Seattle icon.",
    ],
    gettingThere: {
      transit: "Link Light Rail to Stadium Station, right outside the park. Also served by King County Metro buses.",
      parking: "Multiple garages nearby. The SODO area has many affordable lots.",
      rideshare: "Drop-off on Edgar Martinez Drive South. Post-game pickup near 1st Avenue South.",
    },
    stayNearby: {
      budget: { name: "Moore Hotel Seattle", distance: "1.5 mi" },
      midRange: { name: "Hampton Inn Seattle Downtown", distance: "1.2 mi" },
      luxury: { name: "Four Seasons Hotel Seattle", distance: "1.8 mi" },
    },
    nearbyFood: [
      { name: "Pike Place Market", type: "Market", distance: "1.5 mi", note: "The iconic market with fishmongers, produce, and dozens of eateries." },
      { name: "Elliott's Oyster House", type: "Seafood", distance: "1.6 mi", note: "Outstanding Pacific Northwest oysters on the waterfront." },
      { name: "Momofuku Noodle Bar", type: "Ramen / Asian", distance: "1.5 mi", note: "David Chang's acclaimed ramen at Capitol Hill." },
      { name: "Taylor Shellfish Farms", type: "Oyster Bar", distance: "2 mi", note: "The freshest Pacific oysters from a local shellfish legend." },
    ],
    imageColor: "bg-teal-600",
  },
  {
    id: "globe-life-field",
    slug: "globe-life-field",
    name: "Globe Life Field",
    team: "Texas Rangers",
    league: "AL",
    division: "AL West",
    city: "Arlington",
    state: "TX",
    country: "USA",
    capacity: 40518,
    yearOpened: 2020,
    surface: "Artificial Turf",
    roofType: "Retractable",
    coordinates: { lat: 32.7473, lng: -97.0824 },
    description: "Globe Life Field opened in 2020 and was one of the few new stadiums built without fans due to the pandemic. It hosts the Rangers in Texas heat under a fully retractable roof — the first climate-controlled retractable stadium in baseball.",
    funFacts: [
      "The 2020 World Series and 2023 World Series were both held here.",
      "The retractable roof keeps the interior at a cool 72°F even when it's 105°F outside.",
      "The stadium replaced Globe Life Park, which was notable for being brutally hot in summer.",
    ],
    gettingThere: {
      transit: "Trinity Metro Rail to CentrePort/DFW Airport Station, then a short bus ride. Primarily a drive-to stadium.",
      parking: "Adjacent parking garages and surface lots. Very accessible by car.",
      rideshare: "Drop-off and pickup near the main entrance on Randol Mill Road.",
    },
    stayNearby: {
      budget: { name: "La Quinta Inn Arlington", distance: "1.2 mi" },
      midRange: { name: "Loews Arlington Hotel", distance: "0.5 mi" },
      luxury: { name: "Live! by Loews Arlington", distance: "0.3 mi" },
    },
    nearbyFood: [
      { name: "Texas Live!", type: "Entertainment District", distance: "0.2 mi", note: "Entertainment complex with multiple restaurants right next door." },
      { name: "Joe T. Garcia's", type: "Tex-Mex", distance: "15 mi (Fort Worth)", note: "Fort Worth's most beloved Mexican restaurant, open since 1935." },
      { name: "Cattlemen's Steakhouse", type: "Steakhouse", distance: "14 mi (Fort Worth)", note: "Classic Fort Worth stockyards steakhouse." },
      { name: "Pepe's & Mito's", type: "Mexican", distance: "4 mi", note: "Great authentic Mexican close to the stadium." },
    ],
    imageColor: "bg-blue-600",
  },
  {
    id: "truist-park",
    slug: "truist-park",
    name: "Truist Park",
    team: "Atlanta Braves",
    league: "NL",
    division: "NL East",
    city: "Cumberland",
    state: "GA",
    country: "USA",
    capacity: 41084,
    yearOpened: 2017,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 33.8908, lng: -84.4678 },
    description: "Truist Park opened in 2017 in Cumberland (Cobb County), replacing Turner Field in Atlanta. It's the centerpiece of The Battery Atlanta, a mixed-use entertainment complex around the stadium.",
    funFacts: [
      "The Braves won the 2021 World Series at Truist Park.",
      "The Battery Atlanta surrounding the stadium has over 2 million square feet of shops, restaurants, and residences.",
      "The park features a 'Chop House' all-you-can-eat section in left field.",
    ],
    gettingThere: {
      transit: "Game Day Express shuttle from various MARTA rail stations. No direct rail service.",
      parking: "Multiple garages in The Battery. Arrive early — it fills fast.",
      rideshare: "Drop-off at The Battery main plaza. Post-game pickup can be slow — plan for a walk.",
    },
    stayNearby: {
      budget: { name: "Courtyard Atlanta Cumberland", distance: "1 mi" },
      midRange: { name: "Renaissance Atlanta Waverly Hotel", distance: "0.8 mi" },
      luxury: { name: "The Battery Atlanta hotel (Omni)", distance: "0.1 mi" },
    },
    nearbyFood: [
      { name: "The Battery Atlanta", type: "Entertainment District", distance: "0 mi", note: "Dozens of restaurants and bars directly adjacent to the park." },
      { name: "C. Ellet's", type: "Steakhouse", distance: "0.1 mi", note: "Upscale steakhouse inside The Battery." },
      { name: "Fox Bros. Bar-B-Q", type: "BBQ", distance: "8 mi (Atlanta)", note: "Atlanta's best BBQ — Texas-style brisket and ribs." },
      { name: "Varuni Napoli", type: "Pizza", distance: "7 mi (Atlanta)", note: "Excellent Neapolitan pizza, worth the drive." },
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "marlins-park",
    slug: "marlins-park",
    name: "loanDepot Park",
    team: "Miami Marlins",
    league: "NL",
    division: "NL East",
    city: "Miami",
    state: "FL",
    country: "USA",
    capacity: 36742,
    yearOpened: 2012,
    surface: "Natural Grass",
    roofType: "Retractable",
    coordinates: { lat: 25.7781, lng: -80.2197 },
    description: "loanDepot Park (formerly Marlins Park) is a state-of-the-art retractable roof stadium built on the site of the old Orange Bowl. Known for its colorful aquarium behind home plate and bold, artistic interior design.",
    funFacts: [
      "Fish tanks containing live marlins and tropical fish are built into the wall behind home plate.",
      "A colorful kinetic sculpture home run feature was removed in 2012 due to fan complaints.",
      "The stadium sits in Little Havana, one of Miami's most culturally vibrant neighborhoods.",
    ],
    gettingThere: {
      transit: "Miami-Dade Metrorail to Culmer Station (1 mile). Free circulator from Brickell City Centre on select dates.",
      parking: "Surface lots adjacent to the stadium. Affordable by Miami standards.",
      rideshare: "Drop-off and pickup on NW 16th Street.",
    },
    stayNearby: {
      budget: { name: "Miami River Inn", distance: "2 mi" },
      midRange: { name: "Hampton Inn Miami Brickell-Downtown", distance: "3 mi" },
      luxury: { name: "EAST Miami", distance: "3 mi (Brickell)" },
    },
    nearbyFood: [
      { name: "Versailles Restaurant", type: "Cuban", distance: "2.5 mi", note: "The most famous Cuban restaurant in the world, in Little Havana." },
      { name: "El Rey de las Fritas", type: "Cuban Burger", distance: "2 mi", note: "Legendary frita cubana (Cuban burger) in Little Havana." },
      { name: "La Camaronera", type: "Seafood", distance: "2 mi", note: "Shrimp counter institution in Little Havana." },
      { name: "Zak the Baker", type: "Bakery / Deli", distance: "4 mi (Wynwood)", note: "Outstanding artisan bakery and deli." },
    ],
    imageColor: "bg-blue-500",
  },
  {
    id: "citizens-bank-park",
    slug: "citizens-bank-park",
    name: "Citizens Bank Park",
    team: "Philadelphia Phillies",
    league: "NL",
    division: "NL East",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    capacity: 42792,
    yearOpened: 2004,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 39.9061, lng: -75.1665 },
    description: "Citizens Bank Park opened in 2004 and consistently ranks among the best ballparks in baseball. Located in South Philly's sports complex, it sits next to the Eagles' Lincoln Financial Field and Wells Fargo Center.",
    funFacts: [
      "The Liberty Bell home run feature lights up every time a Phillies player hits a home run.",
      "Citizens Bank Park is surrounded by three other major sports venues — all within walking distance.",
      "The ballpark is known for having some of the best food in baseball, including cheesesteaks.",
    ],
    gettingThere: {
      transit: "SEPTA Broad Street Line (Orange Line) to AT&T Station, then a short walk through the sports complex.",
      parking: "Multiple lots in the South Philly sports complex. Arrive early for premium spots.",
      rideshare: "Drop-off at Pattison Avenue. Post-game pickup can take time — plan accordingly.",
    },
    stayNearby: {
      budget: { name: "Courtyard Philadelphia South at The Navy Yard", distance: "2 mi" },
      midRange: { name: "Aloft Philadelphia Downtown", distance: "3.5 mi" },
      luxury: { name: "The Rittenhouse Hotel", distance: "4 mi" },
    },
    nearbyFood: [
      { name: "Geno's Steaks", type: "Cheesesteak", distance: "1.5 mi", note: "The most famous cheesesteak corner in South Philly — open 24/7." },
      { name: "Pat's King of Steaks", type: "Cheesesteak", distance: "1.5 mi", note: "Pat's and Geno's are right across from each other. Pick a side." },
      { name: "Tony Luke's", type: "Cheesesteak / Roast Pork", distance: "1 mi", note: "The roast pork sandwich rivals the cheesesteak." },
      { name: "Federal Donuts", type: "Donuts / Fried Chicken", distance: "3 mi", note: "Michael Solomonov's beloved donut and chicken shop." },
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "nationals-park",
    slug: "nationals-park",
    name: "Nationals Park",
    team: "Washington Nationals",
    league: "NL",
    division: "NL East",
    city: "Washington",
    state: "DC",
    country: "USA",
    capacity: 41313,
    yearOpened: 2008,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 38.8730, lng: -77.0074 },
    description: "Nationals Park opened in 2008 as part of the revitalization of the Navy Yard neighborhood in SE Washington D.C. It's a LEED Silver certified green stadium and hosted the 2018 All-Star Game.",
    funFacts: [
      "Nationals Park was the first LEED-certified sports facility in the world.",
      "The Presidents Race between innings features mascots of past U.S. Presidents running around the bases.",
      "The Navy Yard neighborhood has transformed into one of DC's trendiest areas since the park opened.",
    ],
    gettingThere: {
      transit: "DC Metro Green Line to Navy Yard-Ballpark station — directly outside the stadium. A+",
      parking: "Limited nearby parking — take Metro. Garages off N Street available.",
      rideshare: "Drop-off on Potomac Avenue SW. Post-game pickup near the Half Street entrance.",
    },
    stayNearby: {
      budget: { name: "Hyatt House Washington DC/The Wharf", distance: "1.5 mi" },
      midRange: { name: "Canopy by Hilton Washington DC The Wharf", distance: "1.5 mi" },
      luxury: { name: "Pendry Washington DC The Wharf", distance: "2 mi" },
    },
    nearbyFood: [
      { name: "The Anthem / The Wharf", type: "Waterfront District", distance: "1.5 mi", note: "DC's hottest new waterfront development with many restaurants." },
      { name: "Hank's Oyster Bar", type: "Seafood", distance: "0.4 mi", note: "Great oyster bar near the ballpark." },
      { name: "Whaley's", type: "Seafood / Bar", distance: "0.3 mi", note: "Good local restaurant within walking distance of the park." },
      { name: "Ben's Chili Bowl", type: "American", distance: "2.5 mi (U St)", note: "DC institution since 1958 — the half-smoke is essential." },
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "wrigley-field",
    slug: "wrigley-field",
    name: "Wrigley Field",
    team: "Chicago Cubs",
    league: "NL",
    division: "NL Central",
    city: "Chicago",
    state: "IL",
    country: "USA",
    capacity: 41649,
    yearOpened: 1914,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 41.9484, lng: -87.6553 },
    description: "Wrigley Field is the second-oldest ballpark in baseball and one of the most iconic sporting venues in the world. Home of the ivy-covered outfield walls and the famous hand-turned scoreboard, it's a pilgrimage destination for baseball fans.",
    funFacts: [
      "The ivy on the outfield walls was planted in 1937 by Bill Veeck and is protected by ground rules.",
      "Wrigley Field is the last ballpark with a hand-operated scoreboard — it has been updated manually every game since 1937.",
      "The Cubs broke a 108-year World Series drought here in 2016.",
    ],
    gettingThere: {
      transit: "CTA Red Line to Addison Station — right at the front of the park. Chicago's best ballpark transit.",
      parking: "Very limited. Walking or transit strongly recommended. Wrigleyville has neighborhood lots.",
      rideshare: "Drop-off on Addison Street. Post-game is chaotic — be prepared to walk a few blocks.",
    },
    stayNearby: {
      budget: { name: "Wrigley Hostel", distance: "0.2 mi" },
      midRange: { name: "Hotel Zachary", distance: "0.1 mi" },
      luxury: { name: "Viceroy Chicago", distance: "2 mi" },
    },
    nearbyFood: [
      { name: "Murphy's Bleachers", type: "Bar / Grill", distance: "0.1 mi", note: "The classic Cubs pregame bar for decades." },
      { name: "Smoke Daddy BBQ", type: "BBQ", distance: "0.3 mi", note: "Live blues and great ribs in Wrigleyville." },
      { name: "Portillo's", type: "Chicago Style", distance: "0.8 mi", note: "Legendary Chicago hot dogs and Italian beef sandwiches." },
      { name: "Gino's East", type: "Deep Dish Pizza", distance: "4 mi", note: "Chicago deep dish that takes 45 minutes but is worth it." },
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "great-american-ball-park",
    slug: "great-american-ball-park",
    name: "Great American Ball Park",
    team: "Cincinnati Reds",
    league: "NL",
    division: "NL Central",
    city: "Cincinnati",
    state: "OH",
    country: "USA",
    capacity: 42319,
    yearOpened: 2003,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 39.0974, lng: -84.5067 },
    description: "Great American Ball Park opened in 2003 on the Ohio River, replacing Riverfront Stadium. It features a beautiful riverfront setting and a Gap Band steam stack that shoots fireworks and steam when a Red hits a home run.",
    funFacts: [
      "The two steam stacks, 'Rosie Red' and 'Mr. Red,' are iconic features of the Cincinnati skyline.",
      "The park has excellent views of the Ohio River and the Newport, KY skyline.",
      "Pete Rose holds the all-time hits record — 4,256 — and is celebrated throughout the park.",
    ],
    gettingThere: {
      transit: "Cincinnati Bell Connector streetcar runs nearby. Limited transit — most fans drive.",
      parking: "Multiple garages and lots near the park. Under the Brent Spence Bridge is a fan favorite.",
      rideshare: "Drop-off on Joe Nuxhall Way. Post-game pickup on Second Street.",
    },
    stayNearby: {
      budget: { name: "21c Museum Hotel Cincinnati", distance: "0.7 mi" },
      midRange: { name: "Hilton Cincinnati Netherland Plaza", distance: "0.6 mi" },
      luxury: { name: "The Cincinnatian Hotel", distance: "0.7 mi" },
    },
    nearbyFood: [
      { name: "Skyline Chili", type: "Cincinnati Chili", distance: "0.5 mi", note: "Cincinnati chili over spaghetti — you must try it even if skeptical." },
      { name: "Montgomery Inn Boathouse", type: "Ribs", distance: "0.3 mi", note: "Legendary Cincinnati BBQ ribs on the Ohio River." },
      { name: "The Eagle OTR", type: "Fried Chicken", distance: "1.5 mi", note: "Best fried chicken in Cincinnati, in the OTR neighborhood." },
      { name: "Boca", type: "European", distance: "1.5 mi", note: "Upscale special-occasion restaurant in OTR." },
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "american-family-field",
    slug: "american-family-field",
    name: "American Family Field",
    team: "Milwaukee Brewers",
    league: "NL",
    division: "NL Central",
    city: "Milwaukee",
    state: "WI",
    country: "USA",
    capacity: 41700,
    yearOpened: 2001,
    surface: "Natural Grass",
    roofType: "Retractable",
    coordinates: { lat: 43.0280, lng: -87.9712 },
    description: "American Family Field (formerly Miller Park) features a fan-shaped retractable roof that can open or close in 10 minutes. It's the largest retractable roof stadium in baseball by square footage.",
    funFacts: [
      "The roof is a fan-shaped design — unique in baseball — that allows the walls to open as well.",
      "Bernie Brewer slides down a yellow slide into a beer mug when the Brewers hit a home run.",
      "Milwaukee has a strong tailgating culture — the lots open 3 hours before first pitch.",
    ],
    gettingThere: {
      transit: "Milwaukee County Transit System buses run on game days. Primarily a drive-to stadium.",
      parking: "Stadium lots surround the park. Tailgating is a major attraction — arrive early.",
      rideshare: "Drop-off on South 70th Street. Post-game pickup near the Miller Park Way entrance.",
    },
    stayNearby: {
      budget: { name: "The Brewhouse Inn & Suites", distance: "4 mi (downtown)" },
      midRange: { name: "Aloft Milwaukee Downtown", distance: "4.5 mi" },
      luxury: { name: "The Pfister Hotel Milwaukee", distance: "5 mi" },
    },
    nearbyFood: [
      { name: "Sobelman's Pub & Grill", type: "Burgers / Bar", distance: "4 mi", note: "Milwaukee's best burger and a Bloody Mary with a whole chicken." },
      { name: "Kopps Custard", type: "Frozen Custard", distance: "3 mi", note: "Milwaukee's legendary frozen custard — flavor of the day." },
      { name: "Milwaukee Public Market", type: "Food Hall", distance: "5 mi", note: "Great variety of local vendors on the Milwaukee River." },
      { name: "Lakefront Brewery", type: "Brewery", distance: "5 mi", note: "One of Milwaukee's great craft breweries." },
    ],
    imageColor: "bg-yellow-600",
  },
  {
    id: "pnc-park",
    slug: "pnc-park",
    name: "PNC Park",
    team: "Pittsburgh Pirates",
    league: "NL",
    division: "NL Central",
    city: "Pittsburgh",
    state: "PA",
    country: "USA",
    capacity: 38362,
    yearOpened: 2001,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 40.4469, lng: -80.0057 },
    description: "PNC Park is widely considered the most beautiful ballpark in baseball. Its views of the Roberto Clemente Bridge and the Pittsburgh skyline across the Allegheny River are breathtaking.",
    funFacts: [
      "The Roberto Clemente Bridge is closed to traffic on game days and becomes a pedestrian walkway to the park.",
      "The right field upper deck is just 88 feet from the foul line — one of the closest in baseball.",
      "Forbes Field, the old Pirates stadium (1909-1970), had a homeplate marker preserved in a nearby building.",
    ],
    gettingThere: {
      transit: "Walk across the Roberto Clemente Bridge from downtown. Port Authority buses also serve the area.",
      parking: "North Shore lots adjacent to the stadium. Also garages across the Clemente Bridge.",
      rideshare: "Drop-off on Federal Street. Post-game pickup on General Robinson Street.",
    },
    stayNearby: {
      budget: { name: "Graduate Pittsburgh", distance: "2 mi" },
      midRange: { name: "Omni William Penn Hotel", distance: "1.5 mi" },
      luxury: { name: "The Fairmont Pittsburgh", distance: "1.5 mi" },
    },
    nearbyFood: [
      { name: "Primanti Brothers", type: "Pittsburgh Sandwich", distance: "0.5 mi (North Shore)", note: "Famous Pittsburgh sandwiches with fries and coleslaw inside." },
      { name: "Butcher & the Rye", type: "American", distance: "1.5 mi", note: "Excellent whiskey bar and restaurant downtown." },
      { name: "Church Brew Works", type: "Brewery", distance: "2.5 mi", note: "Craft brewery in a converted Catholic church." },
      { name: "Gaucho Parrilla Argentina", type: "Argentine BBQ", distance: "0.3 mi", note: "Outstanding wood-fired meats right next to the park." },
    ],
    imageColor: "bg-yellow-500",
  },
  {
    id: "busch-stadium",
    slug: "busch-stadium",
    name: "Busch Stadium",
    team: "St. Louis Cardinals",
    league: "NL",
    division: "NL Central",
    city: "St. Louis",
    state: "MO",
    country: "USA",
    capacity: 44494,
    yearOpened: 2006,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 38.6226, lng: -90.1928 },
    description: "Busch Stadium opened in 2006 with spectacular views of the Gateway Arch. The Cardinals have one of the most passionate fanbases in baseball, and the park sits in the heart of downtown St. Louis.",
    funFacts: [
      "The Gateway Arch is visible from every seat in the outfield.",
      "The Cardinals have won 11 World Series titles — second only to the Yankees.",
      "Stan Musial, Bob Gibson, and Albert Pujols are just some of the Cardinals legends honored at the park.",
    ],
    gettingThere: {
      transit: "MetroLink Light Rail to Busch Stadium Station — directly adjacent to the park.",
      parking: "Multiple garages within 2 blocks. The Stadium East garage is closest.",
      rideshare: "Drop-off on Clark Street. Post-game pickup on Spruce Street.",
    },
    stayNearby: {
      budget: { name: "Drury Inn & Suites St. Louis Convention Center", distance: "0.5 mi" },
      midRange: { name: "Marriott St. Louis Grand", distance: "0.3 mi" },
      luxury: { name: "Four Seasons Hotel St. Louis", distance: "0.6 mi" },
    },
    nearbyFood: [
      { name: "Pappy's Smokehouse", type: "BBQ", distance: "2.5 mi", note: "The best BBQ in St. Louis, probably in the Midwest." },
      { name: "Charlie Gitto's on the Hill", type: "Italian", distance: "3 mi", note: "St. Louis Hill neighborhood Italian — an institution." },
      { name: "Sugarfire Smoke House", type: "BBQ", distance: "3 mi", note: "A close second to Pappy's, incredible burnt ends." },
      { name: "Budweiser Brew House", type: "Brewery / Bar", distance: "0.1 mi", note: "Anheuser-Busch brewery bar right next to the stadium." },
    ],
    imageColor: "bg-red-700",
  },
  {
    id: "chase-field",
    slug: "chase-field",
    name: "Chase Field",
    team: "Arizona Diamondbacks",
    league: "NL",
    division: "NL West",
    city: "Phoenix",
    state: "AZ",
    country: "USA",
    capacity: 48686,
    yearOpened: 1998,
    surface: "Natural Grass",
    roofType: "Retractable",
    coordinates: { lat: 33.4453, lng: -112.0667 },
    description: "Chase Field was the first retractable-roof stadium with a natural grass playing surface. The park features a pool and hot tub in right center field — a unique luxury purchase for groups.",
    funFacts: [
      "Chase Field has a swimming pool and hot tub in the right-center field bleachers, available for group purchase.",
      "The Diamondbacks won the 2001 World Series in a legendary Game 7 against Mariano Rivera.",
      "The park is among the largest in baseball by capacity.",
    ],
    gettingThere: {
      transit: "Valley Metro Light Rail to Jefferson/1st Ave Station — right next to the stadium.",
      parking: "Multiple garages adjacent to the park. Arrive early on busy days.",
      rideshare: "Drop-off on Jefferson Street. Post-game pickup on 4th Street.",
    },
    stayNearby: {
      budget: { name: "Cambria Hotel Phoenix Downtown", distance: "0.5 mi" },
      midRange: { name: "Courtyard Phoenix Downtown", distance: "0.3 mi" },
      luxury: { name: "Westin Phoenix Downtown", distance: "0.2 mi" },
    },
    nearbyFood: [
      { name: "Pizzeria Bianco", type: "Pizza", distance: "0.3 mi", note: "Chris Bianco's legendary pizza — worth any wait." },
      { name: "Breakfast Club", type: "American Breakfast", distance: "0.4 mi", note: "Great casual option for a day game." },
      { name: "Barrio Café", type: "Mexican", distance: "2 mi", note: "Award-winning modern Mexican in the Grand Avenue arts district." },
      { name: "Durant's Restaurant", type: "Steakhouse", distance: "1.5 mi", note: "Phoenix institution since 1950 — enter through the kitchen." },
    ],
    imageColor: "bg-purple-700",
  },
  {
    id: "coors-field",
    slug: "coors-field",
    name: "Coors Field",
    team: "Colorado Rockies",
    league: "NL",
    division: "NL West",
    city: "Denver",
    state: "CO",
    country: "USA",
    capacity: 46897,
    yearOpened: 1995,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 39.7559, lng: -104.9942 },
    description: "Coors Field is famous for being at 5,280 feet elevation — a mile high — which makes the ball carry farther, resulting in more home runs. It sits in the LoDo (Lower Downtown) neighborhood, one of Denver's most vibrant areas.",
    funFacts: [
      "Humidor balls are used at Coors Field to reduce the humidification effect of dry, high-altitude air.",
      "The park has a row of purple seats at exactly the one-mile-high elevation mark.",
      "The opening series in 1995 was the first major league games in Colorado.",
    ],
    gettingThere: {
      transit: "RTD Light Rail to Union Station, then a 10-minute walk through LoDo. Or 20th Street stop on the D/F/H lines.",
      parking: "LoDo neighborhood has many parking structures and surface lots.",
      rideshare: "Drop-off on Blake Street. Post-game pickup on Market Street.",
    },
    stayNearby: {
      budget: { name: "The Curtis Denver Hotel", distance: "1 mi" },
      midRange: { name: "The Oxford Hotel Denver", distance: "0.7 mi" },
      luxury: { name: "The Crawford Hotel at Union Station", distance: "0.5 mi" },
    },
    nearbyFood: [
      { name: "Root Down", type: "American", distance: "0.8 mi", note: "Seasonal, local ingredients in a gorgeous LoDo space." },
      { name: "The Wynkoop Brewing Company", type: "Brewery", distance: "0.5 mi", note: "Denver's oldest brewpub, founded by John Hickenlooper." },
      { name: "Rioja", type: "Mediterranean", distance: "0.3 mi", note: "Larimer Square gem — one of Denver's best restaurants." },
      { name: "Denver Milk Market", type: "Food Hall", distance: "0.7 mi", note: "18 local vendors in a beautiful historic creamery building." },
    ],
    imageColor: "bg-purple-700",
  },
  {
    id: "dodger-stadium",
    slug: "dodger-stadium",
    name: "Dodger Stadium",
    team: "Los Angeles Dodgers",
    league: "NL",
    division: "NL West",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    capacity: 56000,
    yearOpened: 1962,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 34.0739, lng: -118.2400 },
    description: "Dodger Stadium is the third-oldest ballpark in baseball and the largest by capacity. Situated in Elysian Park with views of the downtown LA skyline and surrounding hills, it is one of the most beautiful settings in sports.",
    funFacts: [
      "Dodger Stadium is the third-largest stadium in baseball and consistently leads MLB in attendance.",
      "The Dodger Dog has been a baseball food icon since 1962.",
      "Sandy Koufax, Jackie Robinson (via Brooklyn), and Fernando Valenzuela are among the Dodgers legends.",
    ],
    gettingThere: {
      transit: "Dodger Stadium Express bus from Union Station (Metro Gold/A Line and other Metro lines) — highly recommended.",
      parking: "Massive parking lots around the stadium. Efficient system — follow the color-coded signs.",
      rideshare: "Drop-off at Vin Scully Avenue. Post-game pickup is congested — Lyft Lane is designated.",
    },
    stayNearby: {
      budget: { name: "Freehand Los Angeles", distance: "3 mi" },
      midRange: { name: "Line Hotel LA", distance: "3.5 mi" },
      luxury: { name: "NoMad Hotel Los Angeles", distance: "3.5 mi (Downtown)" },
    },
    nearbyFood: [
      { name: "Grand Central Market", type: "Food Hall", distance: "2 mi", note: "LA's great democratic food hall since 1917 — incredible variety." },
      { name: "Langer's Deli", type: "Jewish Deli", distance: "2 mi", note: "Jonathan Gold called the pastrami here the best in the world." },
      { name: "Guerrilla Tacos", type: "Tacos", distance: "3 mi", note: "Chef Wes Avila's tacos are unlike anything else in LA." },
      { name: "Clifton's Republic", type: "American", distance: "2 mi", note: "Historic downtown LA destination with multiple floors and bars." },
    ],
    imageColor: "bg-blue-700",
  },
  {
    id: "petco-park",
    slug: "petco-park",
    name: "Petco Park",
    team: "San Diego Padres",
    league: "NL",
    division: "NL West",
    city: "San Diego",
    state: "CA",
    country: "USA",
    capacity: 40209,
    yearOpened: 2004,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 32.7076, lng: -117.1570 },
    description: "Petco Park is consistently rated among the best ballparks in baseball. Built in the heart of the Gaslamp Quarter, it features the historic Western Metal Supply Co. building incorporated into the left-field corner.",
    funFacts: [
      "The Western Metal Supply Co. building (built 1909) was incorporated into the left-field foul pole area.",
      "Petco Park has a Park at the Park beyond center field — a grassy hill area for families.",
      "The weather is nearly perfect year-round in San Diego — open-air baseball at its finest.",
    ],
    gettingThere: {
      transit: "MTS Trolley Blue Line to Gaslamp Quarter station — right at the park. Outstanding transit access.",
      parking: "Multiple garages in the Gaslamp Quarter.",
      rideshare: "Drop-off on Tony Gwynn Drive. Post-game pickup at Imperial Avenue.",
    },
    stayNearby: {
      budget: { name: "500 West Hotel", distance: "0.5 mi" },
      midRange: { name: "Marriott Gaslamp Quarter", distance: "0.3 mi" },
      luxury: { name: "The US Grant Hotel", distance: "0.4 mi" },
    },
    nearbyFood: [
      { name: "Puesto at The Headquarters", type: "Mexican", distance: "0.5 mi", note: "Beautiful modern Mexican in the historic police headquarters." },
      { name: "Juniper & Ivy", type: "New American", distance: "1.5 mi", note: "Rob Ruiz's acclaimed restaurant in Little Italy." },
      { name: "The Crack Shack", type: "Fried Chicken", distance: "1.5 mi", note: "Outstanding fried chicken in Little Italy." },
      { name: "Hodad's", type: "Burgers", distance: "5 mi", note: "San Diego's most beloved burger joint in Ocean Beach." },
    ],
    imageColor: "bg-orange-600",
  },
  {
    id: "oracle-park",
    slug: "oracle-park",
    name: "Oracle Park",
    team: "San Francisco Giants",
    league: "NL",
    division: "NL West",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    capacity: 41915,
    yearOpened: 2000,
    surface: "Natural Grass",
    roofType: "Open",
    coordinates: { lat: 37.7786, lng: -122.3893 },
    description: "Oracle Park (formerly AT&T Park, SBC Park, Pacific Bell Park) sits on the edge of San Francisco Bay. Home runs that clear the right-field wall splash into McCovey Cove, where kayakers wait in 'splash hit' anticipation.",
    funFacts: [
      "Barry Bonds hit 35 splash home runs into McCovey Cove during his career at the park.",
      "The park can be the coldest in baseball in July due to San Francisco's summer fog.",
      "The Grateful Dead's Jerry Garcia is honored with a tie-dye-clad statue outside the park.",
    ],
    gettingThere: {
      transit: "Muni T-Third Street light rail to AT&T Park station. Also ferry service from Jack London Square and the Ferry Building.",
      parking: "Very limited and expensive. Transit or walk from downtown strongly recommended.",
      rideshare: "Drop-off on King Street. Post-game pickup near the 2nd Street entrance.",
    },
    stayNearby: {
      budget: { name: "HI San Francisco City Center Hostel", distance: "1 mi" },
      midRange: { name: "Hotel Vitale", distance: "0.7 mi" },
      luxury: { name: "The St. Regis San Francisco", distance: "0.5 mi" },
    },
    nearbyFood: [
      { name: "The Slanted Door", type: "Vietnamese", distance: "0.7 mi", note: "Charles Phan's acclaimed modern Vietnamese at the Ferry Building." },
      { name: "Bix Restaurant", type: "American", distance: "1.5 mi", note: "Classic supper club in Jackson Square — incredible cocktails." },
      { name: "Fog City Diner", type: "American Diner", distance: "0.7 mi", note: "Upscale diner near the Embarcadero." },
      { name: "Mission Dolores Taquerias", type: "Burritos / Mexican", distance: "2 mi", note: "The Mission District has the best burritos in the world." },
    ],
    imageColor: "bg-orange-500",
  },
];

export function getStadiumBySlug(slug: string): Stadium | undefined {
  return stadiums.find((s) => s.slug === slug);
}

export function getAllSlugs(): string[] {
  return stadiums.map((s) => s.slug);
}

export const divisions = [
  "AL East",
  "AL Central",
  "AL West",
  "NL East",
  "NL Central",
  "NL West",
] as const;

export const surfaces: Surface[] = ["Natural Grass", "Artificial Turf", "Hybrid"];
export const roofTypes: RoofType[] = ["Open", "Fixed Dome", "Retractable", "Partially Open"];
